export const SAVE_PERSONAL_DETAILS = "SAVE_PERSONAL_DETAILS";
export const GET_PERSONAL_DETAILS = "GET_PERSONAL_DETAILS";

export const SAVE_WORKSPACE_DETAIS = "SAVE_WORKSPACE_DETAIS";
export const GET_WORKSPACE_DETAIS = "GET_WORKSPACE_DETAIS";

export const SAVE_USAGE_DETAILS = "SAVE_USAGE_DETAILS";
export const GET_USAGE_DETAILS = "GET_USAGE_DETAILS";

export const SET_CURRENT_STEP = "SET_CURRENT_STEP";
export const GET_CURRENT_STEP = "GET_CURRENT_STEP";
